"""langgraph checkpoints

Revision ID: b75eccea29fc
Revises: 098b82eb713c
Create Date: 2026-10-06 22:34:09.581466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b75eccea29fc'
down_revision: Union[str, Sequence[str], None] = '098b82eb713c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('value', sa.LargeBinary(), nullable=True),
    sa.Column('task_path', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name='pk_checkpoint_writes')
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.LargeBinary(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name='pk_checkpoints')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_writes')
    # ### end Alembic commands ###
