"""code index tables: code_files + code_chunks (halfvec(2048) HNSW + tsvector GIN)

halfvec, not vector: pgvector HNSW indexes cap plain vectors at 2000 dims.

Revision ID: 098b82eb713c
Revises: faaa983951ae
Create Date: 2026-10-06 21:59:38.188363

"""

from typing import Sequence, Union

import pgvector.sqlalchemy.halfvec
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "098b82eb713c"
down_revision: Union[str, Sequence[str], None] = "faaa983951ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_files",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("repo_root", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mtime_ns", sa.BigInteger(), nullable=False),
        sa.Column("embedding_model", sa.String(length=200), nullable=False),
        sa.Column("chunker_version", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_files")),
        sa.UniqueConstraint("repo_root", "path", name="uq_code_files_repo_root_path"),
    )
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("repo_root", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=2048), nullable=False),
        sa.Column("tsv", postgresql.TSVECTOR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["code_files.id"], name=op.f("fk_code_chunks_file_id_code_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_chunks")),
    )
    op.create_index(
        "ix_code_chunks_embedding_hnsw",
        "code_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_index(op.f("ix_code_chunks_file_id"), "code_chunks", ["file_id"], unique=False)
    op.create_index(op.f("ix_code_chunks_repo_root"), "code_chunks", ["repo_root"], unique=False)
    op.create_index("ix_code_chunks_tsv", "code_chunks", ["tsv"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_code_chunks_tsv", table_name="code_chunks", postgresql_using="gin")
    op.drop_index(op.f("ix_code_chunks_repo_root"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_file_id"), table_name="code_chunks")
    op.drop_index(
        "ix_code_chunks_embedding_hnsw",
        table_name="code_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_table("code_chunks")
    op.drop_table("code_files")
    # ### end Alembic commands ###
