"""long-term memory and code graph

Revision ID: 7bbae0269ed9
Revises: b75eccea29fc
Create Date: 2026-10-07 18:12:15.112574

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.halfvec
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bbae0269ed9"
down_revision: Union[str, Sequence[str], None] = "b75eccea29fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memories",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("repo_root", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=2048), nullable=False),
        sa.Column("uses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('fact', 'preference', 'lesson')", name=op.f("ck_memories_kind_valid")),
        sa.CheckConstraint("scope IN ('project', 'user')", name=op.f("ck_memories_scope_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(
        "ix_memories_embedding_hnsw",
        "memories",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_index(op.f("ix_memories_repo_root"), "memories", ["repo_root"], unique=False)
    op.create_table(
        "code_edges",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("repo_root", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('call', 'import')", name=op.f("ck_code_edges_kind_valid")),
        sa.ForeignKeyConstraint(
            ["file_id"], ["code_files.id"], name=op.f("fk_code_edges_file_id_code_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_edges")),
    )
    op.create_index(op.f("ix_code_edges_file_id"), "code_edges", ["file_id"], unique=False)
    op.create_index("ix_code_edges_repo_root_source", "code_edges", ["repo_root", "source"], unique=False)
    op.create_index("ix_code_edges_repo_root_target", "code_edges", ["repo_root", "target"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_code_edges_repo_root_target", table_name="code_edges")
    op.drop_index("ix_code_edges_repo_root_source", table_name="code_edges")
    op.drop_index(op.f("ix_code_edges_file_id"), table_name="code_edges")
    op.drop_table("code_edges")
    op.drop_index(op.f("ix_memories_repo_root"), table_name="memories")
    op.drop_index(
        "ix_memories_embedding_hnsw",
        table_name="memories",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_table("memories")
    # ### end Alembic commands ###
